var searchData=
[
  ['weakrelease',['WeakRelease',['../classgi__lib_1_1_ref_count_object.html#a06fc1d971f6c62d5976ce0417e0125c4',1,'gi_lib::RefCountObject']]],
  ['while0',['WHILE0',['../macros_8h.html#a53c23369af9b81ab3fec5724316eb05c',1,'macros.h']]],
  ['widget',['widget',['../jquery_8js.html#a4af68ff81d322a2563861409a79ff5bf',1,'widget(&quot;ui.mouse&quot;,{options:{cancel:&quot;:input,option&quot;, distance:1, delay:0}, _mouseInit:function(){var d=this;this.element.bind(&quot;mousedown.&quot;+this.widgetName, function(e){return d._mouseDown(e)}).bind(&quot;click.&quot;+this.widgetName, function(e){if(true===b.data(e.target, d.widgetName+&quot;.preventClickEvent&quot;)){b.removeData(e.target, d.widgetName+&quot;.preventClickEvent&quot;);e.stopImmediatePropagation();return false}});this.started=false}, _mouseDestroy:function(){this.element.unbind(&quot;.&quot;+this.widgetName)}, _mouseDown:function(f){if(a){return}(this._mouseStarted &amp;&amp;this._mouseUp(f));this._mouseDownEvent=f;var e=this, g=(f.which==1), d=(typeof this.options.cancel==&quot;string&quot;&amp;&amp;f.target.nodeName?b(f.target).closest(this.options.cancel).length:false);if(!g||d||!this._mouseCapture(f)){return true}this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet){this._mouseDelayTimer=setTimeout(function(){e.mouseDelayMet=true}, this.options.delay)}if(this._mouseDistanceMet(f)&amp;&amp;this._mouseDelayMet(f)){this._mouseStarted=(this._mouseStart(f)!==false);if(!this._mouseStarted){f.preventDefault();return true}}if(true===b.data(f.target, this.widgetName+&quot;.preventClickEvent&quot;)){b.removeData(f.target, this.widgetName+&quot;.preventClickEvent&quot;)}this._mouseMoveDelegate=function(h){return e._mouseMove(h)};this._mouseUpDelegate=function(h){return e._mouseUp(h)};b(document).bind(&quot;mousemove.&quot;+this.widgetName, this._mouseMoveDelegate).bind(&quot;mouseup.&quot;+this.widgetName, this._mouseUpDelegate);f.preventDefault();a=true;return true}, _mouseMove:function(d){if(b.browser.msie &amp;&amp;!(document.documentMode &gt;=9)&amp;&amp;!d.button){return this._mouseUp(d)}if(this._mouseStarted){this._mouseDrag(d);return d.preventDefault()}if(this._mouseDistanceMet(d)&amp;&amp;this._mouseDelayMet(d)){this._mouseStarted=(this._mouseStart(this._mouseDownEvent, d)!==false);(this._mouseStarted?this._mouseDrag(d):this._mouseUp(d))}return!this._mouseStarted}, _mouseUp:function(d){b(document).unbind(&quot;mousemove.&quot;+this.widgetName, this._mouseMoveDelegate).unbind(&quot;mouseup.&quot;+this.widgetName, this._mouseUpDelegate);if(this._mouseStarted){this._mouseStarted=false;if(d.target==this._mouseDownEvent.target){b.data(d.target, this.widgetName+&quot;.preventClickEvent&quot;, true)}this._mouseStop(d)}return false}, _mouseDistanceMet:function(d){return(Math.max(Math.abs(this._mouseDownEvent.pageX-d.pageX), Math.abs(this._mouseDownEvent.pageY-d.pageY))&gt;=this.options.distance)}, _mouseDelayMet:function(d){return this.mouseDelayMet}, _mouseStart:function(d){}, _mouseDrag:function(d){}, _mouseStop:function(d){}, _mouseCapture:function(d){return true}})})(jQuery):&#160;jquery.js'],['../jquery_8js.html#ac118a4c29a2ace98e4c956a7e504390d',1,'Widget():&#160;jquery.js']]],
  ['width',['width',['../structgi__lib_1_1_desktop_profile.html#a0b0e041a89617ee9069e9d3941d5beaa',1,'gi_lib::DesktopProfile::width()'],['../structgi__lib_1_1_window_1_1_on_resized_event_args.html#ae806cd40123485f31ae67aceafab3def',1,'gi_lib::Window::OnResizedEventArgs::width()'],['../structgi__lib_1_1_i_g_p_texture2_d_1_1_from_description.html#aa5e50785bc57e3df4daf51706e64ecb2',1,'gi_lib::IGPTexture2D::FromDescription::width()']]],
  ['win_5fcore_2ecpp',['win_core.cpp',['../win__core_8cpp.html',1,'']]],
  ['win_5fcore_2eh',['win_core.h',['../win__core_8h.html',1,'']]],
  ['win_5finput_2ecpp',['win_input.cpp',['../win__input_8cpp.html',1,'']]],
  ['win_5finput_2eh',['win_input.h',['../win__input_8h.html',1,'']]],
  ['win_5fos_2eh',['win_os.h',['../win__os_8h.html',1,'']]],
  ['window',['Window',['../classgi__lib_1_1windows_1_1_window.html',1,'gi_lib::windows']]],
  ['window',['Window',['../classgi__lib_1_1_window.html#a5163a5e2c52be0434b9877a205268953',1,'gi_lib::Window::Window()'],['../classgi__lib_1_1windows_1_1_window.html#a89d4b5d08c137e4b24cab1b008e9d8e1',1,'gi_lib::windows::Window::Window()'],['../structgi__lib_1_1_window_1_1_on_closed_event_args.html#aea34e6b226e4a68224afd882ec4a5601',1,'gi_lib::Window::OnClosedEventArgs::window()'],['../structgi__lib_1_1_window_1_1_on_resized_event_args.html#af905d86b797b57ad6a2a5c8000786791',1,'gi_lib::Window::OnResizedEventArgs::window()'],['../jquery_8js.html#a3a1b34e910bfab09201cf4cd802439ea',1,'window():&#160;jquery.js']]],
  ['window',['Window',['../classgi__lib_1_1_window.html',1,'gi_lib']]],
  ['windows',['Windows',['../namespacegi__lib.html#a2a318761e1a791726cb93a2ecd728affaaea23489ce3aa9b6406ebb28e0cda430',1,'gi_lib']]],
  ['winmain',['WinMain',['../gi_8cpp.html#ac11a9f698adda87a72e4d287beaabc5f',1,'gi.cpp']]],
  ['world',['world',['../structgi__lib_1_1dx11_1_1_v_s_per_object_buffer.html#a4326c4bc2d67494b0632793633873009',1,'gi_lib::dx11::VSPerObjectBuffer']]],
  ['world_5fview_5fproj',['world_view_proj',['../structgi__lib_1_1dx11_1_1_v_s_per_object_buffer.html#a45ca377dbda06440e268880bb84a77bc',1,'gi_lib::dx11::VSPerObjectBuffer']]],
  ['wrap',['WRAP',['../namespacegi__lib.html#ab402cd08aea2ff2991504998395fd525ae1c8555fcf0ea2bb648a6fd527d658c0',1,'gi_lib']]],
  ['writecookie',['writeCookie',['../resize_8js.html#ad0822459a7d442b8c5e4db795d0aabb4',1,'resize.js']]]
];
